## SETUP
cache:
  paths:
    - ext/

variables:
  GIT_STRATEGY: clone
  PACMAN_INSTALL: pacman -Syq --noconfirm --noprogressbar
  APTGET_INSTALL: apt-get install -y --no-install-recommends
  LIBTORRENT_DEB: https://github.com/althonos/thunar-torrent-property/releases/download/v0.1.0/libtorrent-rasterbar_1.1.3_amd64.deb
  DNF_INSTALL: dnf install -y --refresh

stages:
  - build

## BUILD

.build: &build
  stage: build
  script:
    - mkdir -p build && cd build
    - cmake ..
    - make && make install


###################
# ARCHLINUX       #
###################

build:archlinux-gcc:
  image: library/archlinux
  before_script:
    - $PACMAN_INSTALL base-devel cmake libtorrent-rasterbar thunar gtk2
  <<: *build


###################
# FEDORA          #
###################

build:fedora-gcc:
  image: library/fedora
  before_script:
    - $DNF_INSTALL gtk+-devel cmake gcc Thunar-devel
      rb_libtorrent-devel make gcc-c++
  <<: *build


###################
# UBUNTU          #
###################

build:ubuntu-bionic-gcc:
  image: library/ubuntu:bionic
  before_script:
    - apt-get update -qq
    - $APTGET_INSTALL cmake libthunarx-2-dev libgtk2.0-dev
      libglib2.0-dev build-essential libssl-dev libtorrent-rasterbar-dev
  <<: *build

build:ubuntu-focal-gcc:
  image: library/ubuntu:focal
  before_script:
    - apt-get update -qq
    - $APTGET_INSTALL cmake libthunarx-3-dev libgtk2.0-dev
      libglib2.0-dev build-essential libssl-dev libtorrent-rasterbar-dev
  <<: *build
