## SETUP
cache:
  paths:
    - ext/

variables:
  GIT_STRATEGY: clone
  PACMAN_INSTALL: pacman -Syq --noconfirm --noprogressbar
  APTGET_INSTALL: apt-get install -y --no-install-recommends

stages:
  - build

## BUILD

.build: &build
  stage: build
  script:
    - mkdir -p build && cd build
    - cmake ..
    - make && make install

build:archlinux-gcc:
  image: base/devel
  before_script:
    - $PACMAN_INSTALL cmake libtorrent-rasterbar thunar gtk2 boost
  <<: *build

build:ubuntu-gcc:
  image: library/ubuntu
  allow_failure: true
  before_script:
    - apt-get update -qq
    #- cd ext && bash makedeb-libtorrent-rasterbar.sh && cd ..
    #- dpkg -i ext/libtorrent-rasterbar-git.deb
    - $APTGET_INSTALL cmake libthunarx-2-dev libgtk2.0-dev
      libboost-filesystem-dev libboost-system-dev libglib2.0-dev
      libtorrent-rasterbar-dev build-essential
  <<: *build
