## SETUP
cache:
  paths:
    - ext/

variables:
  GIT_STRATEGY: clone
  PACMAN_INSTALL: pacman -Syq --noconfirm --noprogressbar
  APT_GET_INSTALL: apt-get install -y --no-install-recommends

stages:
  - build

## BUILD

.build: &build
  stage: build
  script:
    - mkdir -p build && cd build
    - cmake ..
    - make && make install

build:archlinux:
  image: base/archlinux
  before_script:
    - $PACMAN_INSTALL cmake make libtorrent-rasterbar thunar gtk2
  <<: *build

build:ubuntu:
  image: library/ubuntu
  before_script:
    - apt-get update -qq
    - cd ext && bash makedeb-libtorrent-rasterbar.sh && cd ..
    - dkpg -i ext/libtorrent-rasterbar-git.deb
    - $APT_GET_INSTALL cmake libthunarx-2-dev libgtk2.0-dev
      libboost-filesystem-dev libboost-system-dev libglib2.0-dev
  <<: *build
