sudo: required
dist: trusty
language: C


compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends
      cmake libthunarx-2-dev libgtk2.0-dev libtorrent-rasterbar-dev
      libboost-filesystem-dev libboost-system-dev

install:
  - mkdir build && cd build
  - cmake ..
  - make
  - make install
